typography_spectrum: 0.052377511747181416
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3484202716499567
  lightness: 0.012394599616527557
  saturation: 0.4900322030298412
  rhythmicContrast: 0.07757321232929826
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5467663705348969
analytics:
  google: null
  facebook: null
  twitter: null
name: Splitlevel
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: pure. creative. design.
description: a rootmotion experience
purpose: []
